"""Added user table

Revision ID: 748cd4446502
Revises: b30a696b2a6e
Create Date: 2024-06-29 03:00:55.701462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '748cd4446502'
down_revision: Union[str, None] = 'b30a696b2a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('methods')
    op.alter_column('sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sessions', 'method_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sessions', 'params',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('sessions', 'time_op',
               existing_type=postgresql.INTERVAL(),
               type_=sa.Float(),
               nullable=False)
    op.drop_constraint('sessions_method_id_fkey', 'sessions', type_='foreignkey')
    op.drop_constraint('sessions_user_id_fkey', 'sessions', type_='foreignkey')
    op.create_unique_constraint(None, 'users', ['login'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_foreign_key('sessions_user_id_fkey', 'sessions', 'users', ['user_id'], ['id'])
    op.create_foreign_key('sessions_method_id_fkey', 'sessions', 'methods', ['method_id'], ['id'])
    op.alter_column('sessions', 'time_op',
               existing_type=sa.Float(),
               type_=postgresql.INTERVAL(),
               nullable=True)
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('sessions', 'params',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('sessions', 'method_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('methods',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('caption', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('json_params', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='methods_pkey')
    )
    # ### end Alembic commands ###
